src/Form/EvalWFDeleteForm.php
<?php
/**
*   The skeleton of this file is from "Creating a configuration entity type in Drupal 8" tutorial
*       @url: https://www.drupal.org/node/1809494
*
*   Drupal’s online documentation is © 2000-2020 by the individual contributors and can be used in accordance with the
*   Creative Commons License,  Attribution-ShareAlike 2.0.
*   PHP code is distributed under the GNU General Public License.
*   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
*
*   @modified by Tóthpál István for EvalWF module
*/

namespace Drupal\evalwf\Form;

use Drupal\Core\Entity\EntityConfirmFormBase;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Builds the form to delete an EvalWF.
 */

class EvalWFDeleteForm extends EntityConfirmFormBase {

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return $this->t('Are you sure you want to delete %name?', array('%name' => $this->entity->label()));
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return parent::getDescription();
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    return new Url('entity.evalwf.collection');
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Delete');
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $form[] = [
      '#type' => 'markup',
      '#markup' => $this->t( 'It will delete all saved data of this evaluation setting.'),
      '#prefix' => '<h3>',
      '#suffix' => '</h3>',
    ];

    switch ($this->entity->getEntityTypeId()) {
      case 'evalwf':
        $wfid = $this->entity->getWebformId();
        $query = \Drupal::entityQuery('evalwf_evaluation')->accessCheck(FALSE)->condition('wfid', $wfid);
        $res = $query->execute();
        if (!empty($res)) {
          $form[] = [
            '#type' => 'markup',
            '#markup' => $this->t( 'These elements also will be deleted, because these are connected to this evaluation settings:' ),
            '#prefix' => '<p>',
            '#suffix' => '</p>',
          ];
          $form['items'] = [
              '#theme' => 'item_list',
              '#title' => $this->t( 'EvalWF Evaluations' ),
              '#items' => []
          ];
          foreach( $res as $eid) {
            $evaluation = \Drupal::entityTypeManager()->getStorage('evalwf_evaluation')->load($eid);
            $form['items']['#items'][] =
              $this->t( '( Id: %eid )  %ts : %wfid', array(
                '%eid' => $eid,
                '%wfid' => $evaluation->getWfId(),
                '%ts' => $evaluation->getTimeStamp()
              ));
          }
          $form[] = [
            '#type' => 'markup',
            '#markup' => $this->t( '%db piece(s)', array( '%db' => count($res) ) ),
            '#prefix' => '<p>',
            '#suffix' => '</p><BR>',
          ];
        }
        break;
      default:
        break;
    }
    $form = parent::buildForm($form, $form_state);

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $this->entity->delete();
    $this->messenger()->addMessage($this->t('Entity %label has been deleted.', array('%label' => $this->entity->label())));

    $form_state->setRedirectUrl($this->getCancelUrl());
  }
}
?>

templates/evalwf-resultpage.html.twig
{#
/**
 *  @file evalwf-resultpage.html.twig
 *
 *  @variables:
 *    - settings:      standard items of the result page
 *    - elements:   webform element and its points in an array
 *    - conditions: conditional link results
 */
#}

{% macro process_elements(elements) %}
  {% for element in elements %}
    {% if element.type in [ 'container', 'details', 'fieldset' ] %}
      <details class="evalwf-element-container" open><summary>{{ element.title }}</summary>
        {% if element.children %}
           {{ _self.process_elements(element.children) }}
        {% endif %}
      </details>
      <div class="evalwf-subtotal">
        <p class="evalwf-subtotal">{{ element.subtotal }}</p>
      </div>
    {% else %}
      <h3 class="evalwf-element-title">{{ element.title }}</h3>
{#
      /** <p>{{ element.type }}</p>  */
#}
      {% if element.description %} <p class="evalwf-element-description">{{ element.description }}</p> {% endif %}
      {% if element.header %}
        <table class="evalwf-element-table">
          <thead class="evalwf-element-table-header">
            <tr class="evalwf-element-table-header">
              {% for item in element.header %}
                {% if item is iterable %}
                  <th class="evalwf-element-table-header-item"{{ item.attributes }}>{{ item.data }}</th>
                {% else %}
                  <th class="evalwf-element-table-header-item">{{ item }}</th>
                {% endif %}
              {% endfor %}
            </tr>
          </thead>
          <tbody class="evalwf-element-table-body">
            {% for row in element.rows %}
              <tr class="evalwf-element-table-row">
                {% if row.question %}
                  {% if row.question is iterable %}
                    <td class="evalwf-element-table-row-question"{{ row.question.attributes }}>{{ row.question.data }}</td>
                  {% else %}
                    <td class="evalwf-element-table-row-question">{{ row.question }}</td>
                  {% endif %}
                {% else %}
                  {% if row.order %}
                    <td class="evalwf-element-table-row-order">{{ row.order }}</td>
                    <td class="evalwf-element-table-row-answer">{{ row.answer }}</td>
                    <td class="evalwf-element-table-row-isgood">{{ row.isgood }}</td>
                  {% else %}
                    <td class="evalwf-element-table-row-selected">
                      <input type="checkbox" {% if row.selected %}checked{% endif %} disabled class="evalwf-element-table-row-checkbox">
                    </td>
                    <td class="evalwf-element-table-row-answer">{{ row.answer }}</td>
                    <td class="evalwf-element-table-row-points">{{ row.points }}</td>
                  {% endif %}
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
          <tfoot class="evalwf-element-table-footer">
            <tr class="evalwf-element-table-footer">
              {% for item in element.footer %}
                {% if item is iterable %}
                  <td class="evalwf-element-table-footer-item"{{ item.attributes }}>{{ item.data }}</td>
                {% else %}
                  <td class="evalwf-element-table-footer-item">{{ item }}</td>
                {% endif %}
              {% endfor %}
            </tr>
          </tfoot>
        </table>
      {% else %}
        <div class="evalwf-input-text">
          <p class="evalwf-input-text">{{ element.text }}</p>
        </div>
      {% endif %}
    {% endif %}
  {% endfor %}
{% endmacro %}

<h1 class="evalwf-title">{{ settings.title }}</h1>
<div class="evalwf-content">{{ settings.html }}</div>
<div class="evalwf-elements">{{ _self.process_elements(elements) }}</div>
<div class="evalwf-conditions">
  {% for item in conditions %}
      <p class="evalwf-conditional-item"><a href="{{ item.url }}">{{ item.title }}</a></p>
  {% endfor %}
</div>